### PR TITLE
Snap text

### PR DESCRIPTION
**Pull request by jonlepage**
Add a snap text tool for add preview styles in vscode.

image

Just a new button to make a snap
image

### CODE REVIEW

**Review by bigtimebuddy — CHANGES_REQUESTED** [review]
Thanks for this feature. Couple of things:

- you should destroy your PIXI objects after image has been created
- make sure to prevent double clicks since snap is asynchronous
- for the background, use Texture.WHITE w Sprite and add a tint instead of using Graphics

**Comment by jonlepage** [comment]
will fix as soon as possible
thank you for your intervention and advice.

**Comment by themoonrat** [comment]
Is a compressed jpg the right way? I'd prefer a png, to ensure the output file is exactly the same as what is seen.

Also, this won't work in IE or Edge, they'll need a polyfil, I believe. If we care about them. (maybe not, with Edge moving to Chromium very soon)

**Comment by jonlepage** [comment]
@themoonrat 
I'm was little worried about png weight, but it look fine, a also add a alpha manager for people don't want background or customize.
i think all should be fine now, tell me if need more change.

**Comment by jonlepage** [comment]
tested on edge beta and it work fine
image
Also tested on vivaldi(chromium), and firefox.

**Comment by jonlepage** [comment]
normally in another kind architecture logic, I will know how to easily prevent a double clicks, but here I have no other idea to perform this more clean.

Am not very good in html content but if you think you have a better idea let me know !

**Comment by bigtimebuddy** [comment]
Closing in favor of #18

**Pull request closed without merging**
